name       : wildmidi
version    : 0.4.3
release    : 3
source     :
    - https://github.com/Mindwerks/wildmidi/archive/wildmidi-0.4.3.tar.gz : 498e5a96455bb4b91b37188ad6dcb070824e92c44f5ed452b90adbaec8eef3c5
license    :
    - GPL-3.0-or-later
    - LGPL-3.0-or-later
component  : programming.library
summary    : WildMIDI is a simple software midi player which has a core softsynth library that can be use with other applications
description: |
    WildMIDI is a simple software midi player which has a core softsynth library that can be use with other applications
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
