name       : wildmidi
version    : 0.3.10
release    : 1
source     :
    - https://github.com/Mindwerks/wildmidi/archive/wildmidi-0.3.10.tar.gz : 0da531586bc8e4e98069265b8762b34855006a23f8d929b59abebf5d0192950e
license    : 
    - GPL-3.0
    - LGPL-3.0
component  : programming
summary    : WildMIDI is a simple software midi player which has a core softsynth library that can be use with other applications
description: |
    WildMIDI is a simple software midi player which has a core softsynth library that can be use with other applications
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
